import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Hero } from "../components";
import { IntroductionSection } from "../components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <IntroductionSection />
    </div>
  );
}
